name: Build CatAPI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore src/CatApi.csproj
    - name: Build
      run: dotnet build src/CatApi.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test test/CatApi.Test.csproj --collect:"XPlat Code Coverage"
